version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"  # Backend API
    volumes:
      - ./backend:/app
      - rust_cache:/usr/local/cargo/registry
    environment:
      - DATABASE_URL=postgresql://pondera:pondera@db:5432/pondera
      - RUST_LOG=debug
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pondera
      - POSTGRES_PASSWORD=pondera
      - POSTGRES_DB=pondera
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  rust_cache: